### ISSUE TITLE
HDR mode hangs the whole application on XA2

### ISSUE THREAD

**Issue by ferlanero** [piggz/harbour-advanced-camera#56]
Is anyone capable of using the HDR mode in Xperia XA2? Selecting it, just make photo animation but app never saves it even hanging the whole application

**Comment by raketti** [comment]
Confirmed on my XA2 (H4113).

- Change the mode to HDR
- Take a photo
- Image finder freezes (UI responds though, mode can be changed)
- No photo is saved

**Comment by dfstorm** [comment]
same as raketti for me. XA2 plus.

**Comment by piggz** [comment]
I understand this is fixed on the XA2 now?

**Comment by raketti** [comment]
Well for me the 0.3.0-1 still freezes when taking a photo with HDR turned on.

**Comment by piggz** [comment]
This is the issue, the xa2, not my app.  I undertstand it will be in a future sfos release,  https://github.com/sonyxperiadev/camera/pull/115

**Comment by raketti** [comment]
Ok, so this can be closed.
